import { AdminEmpty } from "../shared/admin-empty";
import { formatMoney } from "@/domain/money";
import type { CurrencyCode } from "@/domain/constants";

type OrderRow = { id: string; reference: string; email: string; currency: string; subtotalAmount: number; discountAmount: number; totalAmount: number; couponCode: string | null; affiliateCode: string | null; affiliateCommissionBps: number | null; status: string; createdAt: Date; items: Array<{ productTitle: string; quantity: number }>; payments: Array<{ provider: string; environment: string; status: string; providerReference: string }> };
export function OrdersTable({ orders }: { orders: OrderRow[] }) {
  if (!orders.length) return <AdminEmpty title="No orders yet" description="Paid and pending orders will appear here as customers check out." />;
  return <div className="overflow-hidden rounded-[28px] border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[.1em] text-slate-400"><tr><th className="px-5 py-4">Order</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Items</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Promotion / affiliate</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{orders.map((order) => <tr key={order.id}><td className="px-5 py-5"><p className="font-black text-slate-950">{order.reference}</p><p className="mt-1 text-xs text-slate-400">{order.payments[0] ? `${order.payments[0].provider} · ${order.payments[0].environment} · ${order.payments[0].status}` : "No payment"}</p></td><td className="px-5 py-5 text-slate-600">{order.email}</td><td className="px-5 py-5 text-slate-600">{order.items.map((item) => `${item.productTitle} ×${item.quantity}`).join(", ")}</td><td className="px-5 py-5 font-black text-slate-900"><p>{formatMoney(order.totalAmount, order.currency as CurrencyCode, "en")}</p>{order.discountAmount > 0 ? <p className="mt-1 text-xs font-medium text-emerald-700">{formatMoney(order.subtotalAmount, order.currency as CurrencyCode, "en")} subtotal · -{formatMoney(order.discountAmount, order.currency as CurrencyCode, "en")}</p> : null}</td><td className="px-5 py-5 text-xs text-slate-500"><p>Coupon: <span className="font-mono text-slate-700">{order.couponCode ?? "—"}</span></p><p className="mt-1">Affiliate: <span className="font-mono text-slate-700">{order.affiliateCode ?? "—"}</span>{order.affiliateCommissionBps !== null ? ` · ${order.affiliateCommissionBps / 100}% snapshot` : ""}</p></td><td className="px-5 py-5"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{order.status}</span></td><td className="px-5 py-5 text-slate-500">{order.createdAt.toLocaleString("en-NG")}</td></tr>)}</tbody></table></div></div>;
}
