"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export function ProductBasicsForm({ product }: { product: { id: string; slug: string; category: string; status: string; featured: boolean } }) {
  const router = useRouter(); const [slug, setSlug] = useState(product.slug); const [category, setCategory] = useState(product.category); const [status, setStatus] = useState(product.status); const [featured, setFeatured] = useState(product.featured); const [message, setMessage] = useState<string | null>(null);
  async function save() { setMessage(null); const response = await fetch(`/api/admin/products/${product.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug, category, status, featured }) }); const data = (await response.json()) as { error?: string }; setMessage(response.ok ? "Saved." : data.error || "Unable to save."); if (response.ok) router.refresh(); }
  return <section className="rounded-[26px] border border-slate-200 bg-white p-6"><h2 className="text-lg font-black text-slate-950">Product settings</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold text-slate-600">Slug<input value={slug} onChange={(e) => setSlug(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-[#0064E0]" /></label><label className="text-sm font-bold text-slate-600">Category<input value={category} onChange={(e) => setCategory(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-[#0064E0]" /></label><label className="text-sm font-bold text-slate-600">Status<select value={status} onChange={(e) => setStatus(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal"><option>DRAFT</option><option>COMING_SOON</option><option>ACTIVE</option><option>ARCHIVED</option></select></label><label className="mt-7 flex items-center gap-3 text-sm font-bold text-slate-600"><input type="checkbox" checked={featured} onChange={(e) => setFeatured(e.target.checked)} /> Featured product</label></div><div className="mt-5 flex items-center gap-3"><button type="button" onClick={save} className="rounded-full bg-slate-950 px-5 py-2.5 text-sm font-bold text-white">Save settings</button>{message ? <span className="text-sm text-slate-500">{message}</span> : null}</div></section>;
}
