"use client";

import { useState } from "react";

type Translation = { locale: string; title: string; shortDescription: string; description: string | null };
const locales = [["en","English"],["fr","French"],["ar","Arabic"]] as const;
export function ProductTranslationForm({ productId, translations }: { productId: string; translations: Translation[] }) {
  const [locale, setLocale] = useState("en");
  const [drafts, setDrafts] = useState<Record<string, Translation>>(() => Object.fromEntries(locales.map(([code]) => [code, translations.find((item) => item.locale === code) ?? { locale: code, title: "", shortDescription: "", description: "" }])));
  const [message, setMessage] = useState<string | null>(null); const draft = drafts[locale]!;
  const set = (field: keyof Translation, value: string) => setDrafts((all) => ({ ...all, [locale]: { ...all[locale]!, [field]: value } }));
  async function save() { setMessage(null); const response = await fetch(`/api/admin/products/${productId}/translations`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); const data = (await response.json()) as { error?: string }; setMessage(response.ok ? "Translation saved." : data.error || "Unable to save."); }
  return <section className="rounded-[26px] border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-medium text-slate-950">Translated product copy</h2><div className="flex rounded-full bg-slate-100 p-1">{locales.map(([code,label]) => <button key={code} type="button" onClick={() => setLocale(code)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${locale===code ? "bg-white text-slate-950 shadow-sm" : "text-slate-500"}`}>{label}</button>)}</div></div><div className="mt-5 grid gap-4"><label className="text-sm font-medium text-slate-600">Title<input value={draft.title} onChange={(e) => set("title", e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-[#0064E0]" /></label><label className="text-sm font-medium text-slate-600">Short description<textarea value={draft.shortDescription} onChange={(e) => set("shortDescription", e.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-[#0064E0]" /></label><label className="text-sm font-medium text-slate-600">Full description<textarea value={draft.description ?? ""} onChange={(e) => set("description", e.target.value)} rows={6} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-[#0064E0]" /></label></div><div className="mt-5 flex items-center gap-3"><button type="button" onClick={save} disabled={!draft.title || !draft.shortDescription} className="rounded-full bg-slate-950 px-5 py-2.5 text-sm font-medium text-white disabled:opacity-40">Save {locale.toUpperCase()}</button>{message ? <span className="text-sm text-slate-500">{message}</span> : null}</div></section>;
}
