"use client";

import { useState } from "react";
import { CURRENCIES, type CurrencyCode } from "@/domain/constants";
import { decimalMajorToMinor, minorToMajorString } from "@/domain/money";

type Price = { currency: string; amountMinor: number; isActive: boolean };
export function ProductPricesForm({ productId, prices }: { productId: string; prices: Price[] }) {
  const [values, setValues] = useState<Record<CurrencyCode, { amount: string; active: boolean }>>(() => Object.fromEntries(CURRENCIES.map((currency) => { const found = prices.find((p) => p.currency === currency); return [currency, { amount: found ? minorToMajorString(found.amountMinor) : "", active: found?.isActive ?? false }]; })) as Record<CurrencyCode, { amount: string; active: boolean }>);
  const [message, setMessage] = useState<string | null>(null);
  async function save(currency: CurrencyCode) { setMessage(null); try { const item = values[currency]; const amountMinor = item.amount.trim() ? decimalMajorToMinor(item.amount) : 0; const response = await fetch(`/api/admin/products/${productId}/prices`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ currency, amountMinor, isActive: item.active && amountMinor > 0 }) }); const data = (await response.json()) as { error?: string }; setMessage(response.ok ? `${currency} price saved.` : data.error || "Unable to save."); } catch (error) { setMessage(error instanceof Error ? error.message : "Invalid price."); } }
  return <section className="rounded-[26px] border border-slate-200 bg-white p-6"><h2 className="text-lg font-black text-slate-950">Currency pricing</h2><p className="mt-2 text-sm leading-6 text-slate-500">Prices are explicit per currency. No exchange rate is guessed.</p><div className="mt-5 grid gap-3">{CURRENCIES.map((currency) => <div key={currency} className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-[80px_1fr_auto_auto] sm:items-center"><strong className="text-sm">{currency}</strong><input value={values[currency].amount} onChange={(e) => setValues((all) => ({ ...all, [currency]: { ...all[currency], amount: e.target.value } }))} placeholder="0.00" inputMode="decimal" className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none" /><label className="flex items-center gap-2 text-xs font-bold text-slate-500"><input type="checkbox" checked={values[currency].active} onChange={(e) => setValues((all) => ({ ...all, [currency]: { ...all[currency], active: e.target.checked } }))} /> Active</label><button type="button" onClick={() => save(currency)} className="rounded-full bg-white px-4 py-2 text-xs font-bold text-slate-700 shadow-sm">Save</button></div>)}</div>{message ? <p className="mt-4 text-sm text-slate-500">{message}</p> : null}</section>;
}
