name = "octalve-vault-download"
main = "src/index.ts"
compatibility_date = "2026-09-26"

[[r2_buckets]]
binding = "VAULT_ASSETS"
bucket_name = "octalve-vault-assets"

[vars]
ORIGIN_API_URL = "https://vault.octalve.com"

[secrets]
required = [
  "OCTALVE_INTERNAL_REDEEM_SECRET",
  "OCTALVE_INTERNAL_CRON_SECRET"
]

[triggers]
crons = ["*/5 * * * *"]
[[routes]]
pattern = "downloads.octalve.com"
custom_domain = true